// Mocks generated by Mockito 5.3.2 from annotations
// in pencarian/test/helpers/serialtv/serialtv_test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i16;
import 'dart:typed_data' as _i17;

import 'package:core/core.dart' as _i7;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:serialtv/data/datasources/db/serialtv_database_helper.dart'
    as _i14;
import 'package:serialtv/data/datasources/serialtv_local_data_source.dart'
    as _i12;
import 'package:serialtv/data/datasources/serialtv_remote_data_source.dart'
    as _i10;
import 'package:serialtv/data/models/serialtv_detail_response.dart' as _i3;
import 'package:serialtv/data/models/serialtv_model.dart' as _i11;
import 'package:serialtv/data/models/serialtv_table.dart' as _i13;
import 'package:serialtv/domain/entities/serialtv.dart' as _i8;
import 'package:serialtv/domain/entities/serialtv_detail.dart' as _i9;
import 'package:serialtv/domain/repositories/serialtv_repository.dart' as _i5;
import 'package:sqflite/sqflite.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSerialTvDetailResponse_1 extends _i1.SmartFake
    implements _i3.SerialTvDetailResponse {
  _FakeSerialTvDetailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_3 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SerialTvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSerialTvRepository extends _i1.Mock
    implements _i5.SerialTvRepository {
  MockSerialTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>
      getNowPlayingSerialTv() => (super.noSuchMethod(
            Invocation.method(
              #getNowPlayingSerialTv,
              [],
            ),
            returnValue:
                _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>.value(
                    _FakeEither_0<_i7.Failure, List<_i8.SerialTv>>(
              this,
              Invocation.method(
                #getNowPlayingSerialTv,
                [],
              ),
            )),
          ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>
      getSerialTvPopuler() => (super.noSuchMethod(
            Invocation.method(
              #getSerialTvPopuler,
              [],
            ),
            returnValue:
                _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>.value(
                    _FakeEither_0<_i7.Failure, List<_i8.SerialTv>>(
              this,
              Invocation.method(
                #getSerialTvPopuler,
                [],
              ),
            )),
          ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>
      getSerialTvTopRated() => (super.noSuchMethod(
            Invocation.method(
              #getSerialTvTopRated,
              [],
            ),
            returnValue:
                _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>.value(
                    _FakeEither_0<_i7.Failure, List<_i8.SerialTv>>(
              this,
              Invocation.method(
                #getSerialTvTopRated,
                [],
              ),
            )),
          ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, _i9.DetailSerialTv>> getDetailSerialTv(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailSerialTv,
          [id],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, _i9.DetailSerialTv>>.value(
                _FakeEither_0<_i7.Failure, _i9.DetailSerialTv>(
          this,
          Invocation.method(
            #getDetailSerialTv,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i9.DetailSerialTv>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>
      getRecommendationsSerialTv(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getRecommendationsSerialTv,
              [id],
            ),
            returnValue:
                _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>.value(
                    _FakeEither_0<_i7.Failure, List<_i8.SerialTv>>(
              this,
              Invocation.method(
                #getRecommendationsSerialTv,
                [id],
              ),
            )),
          ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>> searchSerialTv(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchSerialTv,
          [query],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>.value(
                _FakeEither_0<_i7.Failure, List<_i8.SerialTv>>(
          this,
          Invocation.method(
            #searchSerialTv,
            [query],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, String>> saveWatchlistSerialTv(
          _i9.DetailSerialTv? serialtv) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlistSerialTv,
          [serialtv],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, String>>.value(
            _FakeEither_0<_i7.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlistSerialTv,
            [serialtv],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, String>>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, String>> removeWatchlistSerialTv(
          _i9.DetailSerialTv? serialtv) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlistSerialTv,
          [serialtv],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, String>>.value(
            _FakeEither_0<_i7.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlistSerialTv,
            [serialtv],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, String>>);
  @override
  _i6.Future<bool> isSerialTvAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isSerialTvAddedToWatchlist,
          [id],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>
      getWatchlistSerialTv() => (super.noSuchMethod(
            Invocation.method(
              #getWatchlistSerialTv,
              [],
            ),
            returnValue:
                _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>.value(
                    _FakeEither_0<_i7.Failure, List<_i8.SerialTv>>(
              this,
              Invocation.method(
                #getWatchlistSerialTv,
                [],
              ),
            )),
          ) as _i6.Future<_i2.Either<_i7.Failure, List<_i8.SerialTv>>>);
}

/// A class which mocks [SerialTvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSerialTvRemoteDataSource extends _i1.Mock
    implements _i10.SerialTvRemoteDataSource {
  MockSerialTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.SerialTvDetailResponse> getDetailSerialTv(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailSerialTv,
          [id],
        ),
        returnValue: _i6.Future<_i3.SerialTvDetailResponse>.value(
            _FakeSerialTvDetailResponse_1(
          this,
          Invocation.method(
            #getDetailSerialTv,
            [id],
          ),
        )),
      ) as _i6.Future<_i3.SerialTvDetailResponse>);
  @override
  _i6.Future<List<_i11.SerialTvModel>> getRecommendationsSerialTv(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendationsSerialTv,
          [id],
        ),
        returnValue:
            _i6.Future<List<_i11.SerialTvModel>>.value(<_i11.SerialTvModel>[]),
      ) as _i6.Future<List<_i11.SerialTvModel>>);
  @override
  _i6.Future<List<_i11.SerialTvModel>> getNowPlayingSerialTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingSerialTv,
          [],
        ),
        returnValue:
            _i6.Future<List<_i11.SerialTvModel>>.value(<_i11.SerialTvModel>[]),
      ) as _i6.Future<List<_i11.SerialTvModel>>);
  @override
  _i6.Future<List<_i11.SerialTvModel>> getSerialTvPopuler() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSerialTvPopuler,
          [],
        ),
        returnValue:
            _i6.Future<List<_i11.SerialTvModel>>.value(<_i11.SerialTvModel>[]),
      ) as _i6.Future<List<_i11.SerialTvModel>>);
  @override
  _i6.Future<List<_i11.SerialTvModel>> getSerialTvTopRated() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSerialTvTopRated,
          [],
        ),
        returnValue:
            _i6.Future<List<_i11.SerialTvModel>>.value(<_i11.SerialTvModel>[]),
      ) as _i6.Future<List<_i11.SerialTvModel>>);
  @override
  _i6.Future<List<_i11.SerialTvModel>> searchSerialTv(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchSerialTv,
          [query],
        ),
        returnValue:
            _i6.Future<List<_i11.SerialTvModel>>.value(<_i11.SerialTvModel>[]),
      ) as _i6.Future<List<_i11.SerialTvModel>>);
}

/// A class which mocks [SerialTvLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSerialTvLocalDataSource extends _i1.Mock
    implements _i12.SerialTvLocalDataSource {
  MockSerialTvLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i13.SerialTvTable?> getSerialTvById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSerialTvById,
          [id],
        ),
        returnValue: _i6.Future<_i13.SerialTvTable?>.value(),
      ) as _i6.Future<_i13.SerialTvTable?>);
  @override
  _i6.Future<List<_i13.SerialTvTable>> getWatchlistSerialTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistSerialTv,
          [],
        ),
        returnValue:
            _i6.Future<List<_i13.SerialTvTable>>.value(<_i13.SerialTvTable>[]),
      ) as _i6.Future<List<_i13.SerialTvTable>>);
  @override
  _i6.Future<String> insertWatchlistSerialTv(_i13.SerialTvTable? serialtv) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlistSerialTv,
          [serialtv],
        ),
        returnValue: _i6.Future<String>.value(''),
      ) as _i6.Future<String>);
  @override
  _i6.Future<String> removeWatchlistSerialTv(_i13.SerialTvTable? serialtv) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlistSerialTv,
          [serialtv],
        ),
        returnValue: _i6.Future<String>.value(''),
      ) as _i6.Future<String>);
}

/// A class which mocks [SerialTvDatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSerialTvDatabaseHelper extends _i1.Mock
    implements _i14.SerialTvDatabaseHelper {
  MockSerialTvDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i15.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i6.Future<_i15.Database?>.value(),
      ) as _i6.Future<_i15.Database?>);
  @override
  _i6.Future<int> insertWatchlistSerialTv(_i13.SerialTvTable? serialtv) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlistSerialTv,
          [serialtv],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);
  @override
  _i6.Future<int> removeWatchlistSerialTv(_i13.SerialTvTable? serialtv) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlistSerialTv,
          [serialtv],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);
  @override
  _i6.Future<Map<String, dynamic>?> getSerialTvById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSerialTvById,
          [id],
        ),
        returnValue: _i6.Future<Map<String, dynamic>?>.value(),
      ) as _i6.Future<Map<String, dynamic>?>);
  @override
  _i6.Future<List<Map<String, dynamic>>> getWatchlistSerialTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistSerialTv,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i16.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i16.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i16.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i16.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i4.Response>);
  @override
  _i6.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<String>.value(''),
      ) as _i6.Future<String>);
  @override
  _i6.Future<_i17.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i17.Uint8List>.value(_i17.Uint8List(0)),
      ) as _i6.Future<_i17.Uint8List>);
  @override
  _i6.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i6.Future<_i4.StreamedResponse>.value(_FakeStreamedResponse_3(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i6.Future<_i4.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
