name: pencarian
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1-nullsafety.2
  equatable: ^2.0.5
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  rxdart: ^0.27.5

  core:
    path: ../core
  film:
    path: ../film
  serialtv:
    path: ../serialtv

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  mocktail: ^0.3.0
  build_runner: ^2.2.1
  bloc_test: ^9.1.0

flutter:

